# Geometric morphometrics

## Load packages + data
```{r load, echo=TRUE, warning = FALSE}
# download most recent software version
#devtools::install_github("geomorphR/geomorph", ref = "Stable", build_vignettes = TRUE)
#devtools::install_github("mlcollyer/RRPP")

# load analysis packages
library(here)
library(StereoMorph)
library(geomorph)
library(ggplot2)
library(dplyr)
library(wesanderson)

# read shape data and define number of sLMs
shapes <- readShapes("shapes")
shapesGM <- readland.shapes(shapes, nCurvePts = c(20))

# read qualitative data
qdata <- read.csv("qdata.csv",
                  header = TRUE,
                  row.names = 1)
```

## Generalised Procrustes Analysis

```{r gpa, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# gpa
Y.gpa <- gpagen(shapesGM, print.progress = FALSE)
plot(Y.gpa)
```

## Boxplot (centroid size)

```{r box, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# dataframe
gdf <- geomorph.data.frame(shape = Y.gpa$coords,
                           size = Y.gpa$Csize,
                           cont = qdata$ context)

# add centroid size to qdata
qdata$csz <- Y.gpa$Csize

# attributes
csz <- qdata$csz
context <- qdata$context

# palette
pal = wes_palette("Moonrise2")

# boxplot of Perdiz arrow points by context
csz.temp <- ggplot(qdata, aes(x = context, y = csz, color = context)) +
  geom_boxplot() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.3) +
  scale_color_manual(values = pal) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = 'Raw Material', y = 'Centroid Size')

# render plot
csz.temp
```

## Principal Components Analysis

```{r pca, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# pca
pca <- gm.prcomp(Y.gpa$coords)
summary(pca)

# set plot parameters
pch.gps <- c(15,17)[as.factor(qdata$context)]
col.gps <- pal[as.factor(qdata$context)]
col.hull <- c("#798E87","#C27D38")

# pca plot
pc.plot <- plot(pca,
                asp = 1,
                pch = pch.gps,
                col = col.gps)
shapeHulls(pc.plot,
           groups = qdata$context,
           group.cols = col.hull)
```

### Minima/maxima of PC1/2

```{r min.max, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# plot x/y maxima/minima
# x - minima
mean.shape <- mshape(Y.gpa$coords)
plotRefToTarget(pca$shapes$shapes.comp1$min, 
                mean.shape)

# x - maxima
plotRefToTarget(pca$shapes$shapes.comp1$max, 
                mean.shape)

# y - minima
plotRefToTarget(pca$shapes$shapes.comp2$min, 
                mean.shape)

# y - maxima
plotRefToTarget(pca$shapes$shapes.comp2$max, 
                mean.shape)
```

## Procrustes ANOVA: Shape and size

```{r ss, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# shape
fit.sh.reg <- procD.lm(shape ~ context,
                       data = gdf,
                       print.progress = FALSE,
                       iter = 9999)

# shape
anova(fit.sh.reg)

# size
fit.sz.reg <- procD.lm(size ~ context,
                       data = gdf,
                       print.progress = FALSE,
                       iter = 9999)

# size
anova(fit.sz.reg)
```

## Allometry

```{r allom, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# allometry (does shape change with size)
fit.size <- procD.lm(shape ~ size,
                     data = gdf,
                     print.progress = FALSE,
                     iter = 9999)

# allometry
anova(fit.size)
```

## Mean shapes

```{r mshape, echo=TRUE, out.width = "100%", dpi = 300, warning=FALSE}
# subset landmark coordinates to produce mean shapes
new.coords <- coords.subset(A = Y.gpa$coords,
                            group = qdata$context)
names(new.coords)

# group shape means
mean <- lapply(new.coords, mshape)

# plot mean shapes
plot(mean$`Pit 434`)
plot(mean$`Structure 23`)

# comparison plots
plotRefToTarget(mean$`Pit 434`,
                mean$`Structure 23`,
                method = "points",
                mag = 1)
```
